[build]
  command = "npm run build:web"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"
  NETLIFY_USE_PNPM = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
